import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

import { extractLexicalText } from '../utilities/extractLexicalText'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // 1. Plain-text body column (auto-generated by Payload from the new
  //    `searchText` field; maintained by the syncSearchText hook from now on).
  await db.execute(sql`
   ALTER TABLE "articles" ADD COLUMN "search_text" varchar;`)

  // 2. Backfill search_text for existing articles. Runs through the Local
  //    API (same transaction via req); disableRevalidate stops the
  //    afterChange hook calling Next.js revalidatePath from a CLI process.
  const articles = await payload.find({
    collection: 'articles',
    limit: 0,
    pagination: false,
    depth: 0,
    req,
  })

  for (const article of articles.docs) {
    await payload.update({
      collection: 'articles',
      id: article.id,
      data: { searchText: extractLexicalText(article.body) },
      depth: 0,
      context: { disableRevalidate: true },
      req,
    })
  }

  // 3. Weighted, generated tsvector + GIN index (Increment 3, CLAUDE.md §2:
  //    Postgres full-text search). Weights: title A, excerpt B, body C.
  //    NOTE: this column is intentionally invisible to Payload/Drizzle —
  //    future auto-generated migrations diff against schema snapshots, not
  //    the live DB, so they will neither see nor drop it.
  await db.execute(sql`
   ALTER TABLE "articles" ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
     setweight(to_tsvector('english', coalesce("title", '')), 'A') ||
     setweight(to_tsvector('english', coalesce("excerpt", '')), 'B') ||
     setweight(to_tsvector('english', coalesce("search_text", '')), 'C')
   ) STORED;
   CREATE INDEX "articles_search_vector_idx" ON "articles" USING gin ("search_vector");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX IF EXISTS "articles_search_vector_idx";
   ALTER TABLE "articles" DROP COLUMN IF EXISTS "search_vector";
   ALTER TABLE "articles" DROP COLUMN "search_text";`)
}
